#!/bin/bash
#================================================================
# HEADER
#================================================================
#%Usage: ${SCRIPT_NAME} [OPTION] [ACTION]
#%A tool to easily create and manage multiple pointers via xinput (MPX)
#%    
#%
#%Options:
#%    -q, --quiet                   Don't display notifications
#%    -m, --master                  set the master to move the target input devices to
#%    -c, --no-create               When loading from the configFile, will not create & attach slaves to master automatically  
#%    -f, --force-create            Create master even if no slaves are available
#%    --no-load                     Do not load settings from file
#%    --file                        Load/Save from/to this file
#%    -h, --help                    Print this help
#%    -i, --ignore-known-slaves     Ignores all slaves. This option is implicitly set when using -n
#%    -v, --version                 Print script information
#%
#%Actions
#%    -r, --reset                   Merge all auxiliary input back into the default master
#%    -d, --dynamic                 Take all input devices that are currently being used and assignment them them to a given master or the next master in the configFile if master is not given
#%    -l, --load                    Restores settings from configFile by attaching all available slaves to the appropriate masters, creating them if needed. This is the default option if no arguments are given
#%    --resume                      The default action. Shorthand for ${SCRIPT_NAME} -c -l
#%    -s, --save                    Restores settings from configFile by attaching all available slaves to the appropriate masters, creating them if needed
#%    -n, --next-master             Assigns all unkown inputs to master
#%    --reload                      Resets and load
#%    --move masterName targets     TODO implement
#%
#%
#%Examples:
#%    ${SCRIPT_NAME} -s             #saves settings
#%    ${SCRIPT_NAME} --master=myMaster -d             #Moves all active inputs to myMaster
#%
#================================================================
#- IMPLEMENTATION
#-    version         ${SCRIPT_NAME} (taaparthur.no-ip.org) 1.1.2
#-    author          Arthur Williams
#-    license         MIT
#================================================================
# END_OF_HEADER
#================================================================


#masters=("Wado Ichimonji" "Sandai Kitetsu" "Yubashiri" "Hana Arashi" "Shusui")

declare -A knownSlaves

#consts
TYPE_MOUSE=1
TYPE_KEYBOARD=2
MATCH_NAME='([\w\/:]+( [\w\/:]+)*)'

numberOfMasterDevices=$(xinput |grep -c "master pointer")
##default settings
quiet=false
createMasterOnLoad=1
loadFromFile=1
ignoreKnownSlaves=0
configFile="$HOME/.config/dualpointerx.conf"

##global vars
masterDevices=()
listOfIDs=()

# create config file if it does not exist
if [[ ! -e "$configFile" ]]; then 
    mkdir -p "$HOME/.config"
    touch "$configFile"    
fi
resume(){
    load
    exit $?
}
load(){
    
    while IFS=$'\t' read -r -a masterDefaults
    do
        listOfIDs=()
        createMaster=1
        masterExists=0
        masterDevices+=("$masterDefaults") #name
        xinput list --id-only "$masterDefaults pointer" &>/dev/null && createMaster=0 && masterExists=1
        
        ## attach all specified slaves to master
        if [[ $loadFromFile ]]; then
            for i in "${masterDefaults[@]:1}"; do
                knownSlaves[$i]="$masterDefaults"
                if [[ $createMaster -eq 1 && $createMasterOnLoad -eq 1 ]]; then 
                    masterExists=1
                    createMaster "$masterDefaults" || masterExists=0
                fi
                
                if [[ $masterExists -eq 1 ]]; then 
                    while IFS=$'\t' read -r -a slaveID; do
                        listOfIDs+=("$slaveID") 
                    done < <(xinput |grep "$i" |perl -lne 'print "$1" if /.*id=(\d*).*slave/')
                fi
                #echo "$masterExists $createMaster"
                
                createMaster=0
            done
            dualWield "$masterDefaults"
        fi
    done < "$configFile"
    listOfIDs=()
}
save(){
    
    declare -A mapMasterToId
    currentMasters=()
    
    while IFS=$'\t' read -r -a masterInfo; do
       currentMasters+=("$masterInfo")
       mapMasterToId["${masterInfo[0]}"]="${masterInfo[1]}"
    done < <(xinput |grep "\\[master " |perl -lne 'print "$4\t$1" if /'"$MATCH_NAME"' (pointer|keyboard).*id=(\d*)/')
    echo -n "" > "$configFile"
    for i in "${currentMasters[@]}"; do 
        printf "%s" "${mapMasterToId[$i]}" >>"$configFile"
        while read -r slaveInfo; do
            printf "\\t%s" "$slaveInfo" >> "$configFile"
        done < <( xinput |grep "\\[slave " |perl -lne 'print "$1" if /'"$MATCH_NAME"'.*\('"$i"'\)/')
        echo "" >> "$configFile"
    done
}

ignoreSlaveDevice(){
    deviceName=$1
    #echo "${knownSlaves[$deviceName]}"
    if [[ $deviceName == *"XTEST"* ]] || echo "$deviceInfo" |grep -q "master"  ; then
        return 0
    elif [[ "$ignoreKnownSlaves" -eq 1 && ${knownSlaves[$deviceName]} ]]; then
        return 0
    else 
        return 1
    fi
}
getNameFromId(){
    xinput list --name-only "$1" 
}
getIdFromName(){
    xinput list --id-only "$1" 
}
getDeviceType(){
    deviceID="$1"
    deviceName=$(getNameFromId "$deviceID" )
    deviceInfo=$(xinput --list "$deviceID")
    #echo "$deviceID $deviceName"
    if ignoreSlaveDevice "$deviceName"; then
        return 0
    elif echo "$deviceInfo" |grep -q "ButtonClass"; then
        return $TYPE_MOUSE
    elif echo "$deviceInfo" |grep -q "KeyClass" ; then
        return $TYPE_KEYBOARD          
    fi
    

}

attachSlaveToMaster(){
    slaveID="$1"
    masterID="$2"
    
    ! xinput list --short "$slaveID" |grep -q "$id" && echo "xinput reattach $slaveID $masterID"  &&  xinput reattach "$slaveID" "$masterID"
}
dualWield() {
	
    miceToEnslave=()
    keyboardsToEnslave=()
    nonEmpty=""
    for i in "${listOfIDs[@]}"; do
        deviceId="$i"
        getDeviceType "$deviceId"
        type=$?
        
        if [[ $type -ne 0 ]] ; then
            nonEmpty=1
            if [[ $type -eq $TYPE_MOUSE ]]; then
               miceToEnslave+=("$deviceId");
            elif [[ $type -eq $TYPE_KEYBOARD ]]; then
               keyboardsToEnslave+=("$deviceId");
            fi
            fi                
    done
    if [[ "$nonEmpty" ]]; then
        if [[ -z $1 ]]; then 
            targetMasterDevice="$(nextMaster)"
            createMaster "$targetMasterDevice"
        else
            targetMasterDevice="$1"
        fi
        
        ## ataching slaves to masters
        id=$(getIdFromName "$targetMasterDevice pointer")
        for device in "${miceToEnslave[@]}"; do
            attachSlaveToMaster "$device" "$id"
        done
        id=$(getIdFromName "$targetMasterDevice keyboard")
        for device in "${keyboardsToEnslave[@]}"; do
            attachSlaveToMaster "$device" "$id"
        done
    else
        return 1
    fi
}
createMaster(){
    if [[ -z $1 ]]; then 
        echo "will not create master with blank name"
        return 1
    elif xinput | grep -q "$1 pointer \\s*id=.*master" ; then
        return 0
    else 
        xinput create-master "$1"
    fi
}

loadCurrentSettings(){
    if [[ "$numberOfMasterDevices" -ne 0 ]] ; then
        while IFS=$'\t' read -r -a master
        do
            masterDevices+=("$master")
        done < <(xinput |grep "master pointer" |perl -lne 'print $1 if /(\w+( [A-Za-z]+)*) pointer.*/')
    else 
        masterDevices=("Virtual core")    
    fi
}
singleWield() {
    ! $quiet && notify "exiting dual wield mode"
    #loadCurrentSettings
    master="$(xinput --list --id-only |head -n1)"
	while IFS=$'\t' read -r -a deviceId; do
	    if [[ "$deviceId" != "$master" ]];then
    	        xinput remove-master "$deviceId" AttachToMaster "$master" #&>/dev/null
	    fi
	done < <(xinput |grep "master pointer" |perl -lne 'print $1 if /id=(\d*)/')
}

nextMaster() {
    if [[ ! -z $nextMaster ]]; then
       echo "$nextMaster"
       return 0
    fi
    for name in "${masterDevices[@]:1}"; do
        if ! xinput |grep "master pointer"|grep "$name" &>/dev/null; then 
        	echo "$name"
        	return 0;
	    fi
    done
    echo "masterDevice$((numberOfMasterDevices+1))"
return 0;
}

readAllIDs() {
    while read -r -a id; do
        listOfIDs+=("$id")
    done < <(xinput list --id-only)
}
readAllMovingIds() {
    exitCode=1

    while read -r deviceId; do
        if read -t .2 < <(timeout .3 xinput test "$deviceId"); then  #if is moving/button click
            listOfIDs+=("$deviceId")
            ! $quiet && echo "moving $deviceId"
            exitCode=0
        fi
    done < <(xinput |grep "slave" |perl -lne 'print "$1" if /id=(\d*)/')
    return $exitCode
}


dynamicAssigment(){
    load
    readAllMovingIds && dualWield
    exit $?
}
moveUnknownsToNextMaster(){
    ignoreKnownSlaves=1
    
    load
    readAllIDs
    echo ${listOfIDs[@]}
    dualWield
}
reset(){
    singleWield
}

SCRIPT_HEADSIZE=$(head -200 ${0} |grep -n "^# END_OF_HEADER" | cut -f1 -d:)
SCRIPT_NAME="$(basename ${0})"

  #== usage functions ==#
usage() { printf "Usage: "; head -${SCRIPT_HEADSIZE:-99} ${0} | grep -e "^#+" | sed -e "s/^#+[ ]*//g" -e "s/\${SCRIPT_NAME}/${SCRIPT_NAME}/g" ; }
usagefull() { head -${SCRIPT_HEADSIZE:-99} ${0} | grep -e "^#[%+]" | sed -e "s/^#[%+-]//g" -e "s/\${SCRIPT_NAME}/${SCRIPT_NAME}/g" ; }
scriptinfo() { head -${SCRIPT_HEADSIZE:-99} ${0} | grep -e "^#-" | sed -e "s/^#-//g" -e "s/\${SCRIPT_NAME}/${SCRIPT_NAME}/g"; }
displayHelp(){
    usagefull
}

version(){
    #scriptinfo
    echo 1.1.2
}

notify(){
    ! $quiet && notify-send "$1"
}


optspec=":hvqpcrsnml:d-:"
while getopts "$optspec" optchar; do
    case "${optchar}" in
        -)
            case "${OPTARG}" in
                next-master)
                    nextMaster
                    ;;
                master=*)
                    val=${OPTARG#*=}
                    nextMaster="$val"
                    ;;
                file)
                    configFile="${OPTARG[1]}"
                    ;;
                help)
                    displayHelp
                    ;;
                version)
                    version
                    ;;
                ignore-known-slaves)
                    ignoreKnownSlaves=1
                    ;;
                no-load)
                    loadFromFile=0
                    ;;
                quiet)
                    quiet=1
                    ;;
                no-create)
                    createMasterOnLoad=0;
                    ;;
                next)
                    moveUnknownsToNextMaster
                    ;;
                resume)
                    createMasterOnLoad=0;
                    resume
                    ;;
                load)
                    resume
                    ;;
                save)
                    save
                    ;;
                reload)
                    reset
                    load
                    ;;
                reset)
                    reset
            		;;
        		dynamic)
                    dynamicAssigment
                    ;;
                *)
                    if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
                        echo "Unknown option --${OPTARG}" >&2
                    fi
                    ;;
            esac;;
        p)
            load
            ;;
        h)
            displayHelp
            exit 0
            ;;
        v)
            version
            ;;
        q)
            quiet=1
            ;;
        c)
            createMasterOnLoad=0;
            ;;
        m)
            nextMaster="${OPTARG}"
            ;;
        n)
            moveUnknownsToNextMaster
            ;;
        i)
            ignoreKnownSlaves=1
            ;;
        l)
            resume
            ;;
        s)
            save
            ;;
        r)
            reset
	        ;;
        d)
            dynamicAssigment
            ;;
        *)
            if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            displayHelp
            ;;
    esac
done

resume
